### ISSUE TITLE
Error occured when CV Bridge compilation with Python 2.7

### ISSUE THREAD

**Issue by ghost** [ros-perception/vision_opencv#238]
OS: Ubuntu 14.04 I'm executing this command: 
`catkin_make -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so`
However, the following error occurred when compiling CVbridge with Python 2.7

`Built target image_geometry
make[2]: *** No rule to make target /usr/lib/libpython2.7.so, needed by /home/kbad10/ros_catkin_ws/devel/lib/python2.7/dist-packages/cv_bridge/boost/cv_bridge_boost.so'.  Stop.
make[1]: *** [vision_opencv/cv_bridge/src/CMakeFiles/cv_bridge_boost.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j4 -l4" failed`

Below is the error screenshot:
![screenshot from 2018-08-02 14 03 21](https://user-images.githubusercontent.com/28727716/43577475-910ec43e-9669-11e8-959c-405d5a2a16d2.png)

Below is the preocess I'm doing:
![screenshot from 2018-08-02 15 21 56](https://user-images.githubusercontent.com/28727716/43577486-95de1532-9669-11e8-8ffe-aadfb4f7cebd.png)

**Comment by ijnek** [comment]
I recently became the maintainer of this repo, and I'm sorting through issues, closing stale ones. As this issue is raised against a platform that is no longer supported in any of the active ros distros, I'm going to close it out. Please feel free to comment if it is still relevant and you would like to get it re-opened.
