### ISSUE TITLE
Infinite far pixels depth set to 1？

### ISSUE THREAD

**Issue by iDsy** [ros-perception/vision_opencv#248]
Hi,

Im using cv_bridge convert ros image to cv::Mat. My code:

void depthImageCallback(const sensor_msgs::ImageConstPtr& msg){
    cv_bridge::CvImagePtr cvImgPtr;
    cv::Mat depthImg;

    try
    {
        cvImgPtr = cv_bridge::toCvCopy(msg, sensor_msgs::image_encodings::TYPE_32FC1);
        depthImg = cvImgPtr->image;
    }
    catch(cv_bridge::Exception& e)
    {
        ROS_ERROR("cv_bridge exception: %s", e.what());
    }

    {// save to file
        ofstream ofs("/home/bamboo/Desktop/depth.txt");
        for (int i = 0; i < 480; ++i)
        {
            for (int j = 0; j < 640; ++j)
            {
                ofs<<depthImg.ptr<float>(i)[j]<<" ";
            }
        }
        ofs.close();
    }
}

I find that the pixels that infinite far were recorded value "1" in depth image. Is this a bug? How to change this kind of infinite pixel value to "0"?

Im running gazebo9, ros melodic, ubuntu 18 to generate these depth images. By rqt I can visualize these depth images. In rqt, infinite far pixels are set to "0".

**Comment by ijnek** [comment]
I recently became the maintainer of this repo, and I'm sorting through issues, closing stale ones. As this issue has not been active for a while, I'm going to close it due to inactivity. Please feel free to comment if it is still relevant and you would like to get it re-opened.

ps. I also believe this is more suited for [ROS Answers](https://answers.ros.org/questions/)
