### ISSUE TITLE
ROS process: terminate called after throwing an instance of 'cv_bridge::Exception'

### ISSUE THREAD

**Issue by BrunoXL** [ros-perception/vision_opencv#253]
On running a ROS node I get the following error below:

    terminate called after throwing an instance of 'cv_bridge::Exception'
    what():  Image is wrongly formed: height * step != size  or  480 * 1920 != 110592

cv_bridge: 1.12.8
opencv: 3.3.1
Machine: Ubuntu 16.04

**Comment by ijnek** [comment]
The error seems to explain the problem clearly. The image your inputting has a wrong shape. Either your width, height, or step of the image is incorrect.

I recently became the maintainer of this repo, and I'm sorting through issues, closing stale ones. As this issue has not been active for a while, I'm going to close it due to inactivity. Please feel free to comment if it is still relevant and you would like to get it re-opened.
