### ISSUE TITLE
double free or corruption (out) when attempting to convert

### ISSUE THREAD

**Issue by JacobJBeck** [ros-perception/vision_opencv#254]
In ROS2 Bouncy, regardless of how I call the conversion (`toCvCopy()` or `toCvShare()`, passing either `Image` or `Image::SharedPtr`), the program crashes with `double free or corruption (out)`.

**Comment by ijnek** [comment]
I recently became the maintainer of this repo, and I'm sorting through issues, closing stale ones. As this issue has not been active for a while, I'm going to close it due to inactivity. Please feel free to comment if it is still relevant and you would like to get it re-opened.

ps. I have not experienced the issue when testing on more recent ros2 distros, so this makes me think its been resolved, or was an issue in your code.
