### ISSUE TITLE
I want to know whether a cv_bridge can only correspond to an opencv version.

### ISSUE THREAD

**Issue by Iampride** [ros-perception/vision_opencv#287]
I want to know whether a cv_bridge can only correspond to an opencv version.

**Comment by mjcarroll** [comment]
Yes, the `cv_bridge` version will correspond to single opencv version.  For example in `melodic` on ubuntu `bionic`, the cv_bridge packages are built to support OpenCV 3.2, the included version.

I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
