### ISSUE TITLE
Kinetic ROS version error

### ISSUE THREAD

**Issue by Fatma-Alshamsi** [ros-perception/vision_opencv#317]
I am following the software- steps from github to download raspbian and ROS from:

http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Kinetic%20on%20the%20Raspberry%20Pi

But when I reach to the command that downloads the kinetic version:

**$ sudo ./src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --install-space /opt/ros/kinetic**

I get this error:
Failed to process package 'qt_gui_cpp': 
  Command '['/opt/ros/kinetic/env.sh', 'make', '-j4', '-l4']' returned non-zero exit status 2

**Comment by mjcarroll** [comment]
I believe that this error is unrelated to `vision_opencv`, as the error itself points to `qt_gui_cpp`

I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
