### ISSUE TITLE
Plumb Bob naming?

### ISSUE THREAD

**Issue by DevonMorris** [ros-perception/vision_opencv#539]
![image](https://github.com/user-attachments/assets/7ed9beca-9984-47e6-b72d-4b1098fd6da6)

This is a plumb bob. How did the name for OpenCV distortion become known as plumb bob? Seems strange to me.

The radial and tangential distortion used by OpenCV is a variant of Brown and Conrady's distortion model originally published in [here](https://academic.oup.com/mnras/article/79/5/384/1078771?login=false) and [here](http://close-range.com/docs/Decentering_Distortion_of_Lenses_Brown_1966_may_444-462.pdf). Furthermore, [OpenCV's camera calibration](https://docs.opencv.org/4.10.0/d9/d0c/group__calib3d.html) documentation does not mention the phrase "plumb bob" as far as I can tell.

I'm curious where this language come from and what it is intended to mean. I believe there is better and more precise language that can be used here and I for one am in favor of being explicit in this regard. For better or worse, ROS's naming here is becoming a _de facto_ standard in the computer vision community and I'd like to understand why and where "plumb bob" comes from.

**Comment by ijnek** [comment]
I don't know the details - had a quick look and I found an older mention of the plumb-bob model in a [matlab camera calibration toolbox (2003)](http://robots.stanford.edu/cs223b04/JeanYvesCalib/htmls/parameters.html). Though it does seem like it was popularized by usage in the ROS community.

Since this is a question, i will close it out to reduce the number of open issues. (Feel free to continue the discussion though.)
